[package]
name = "borrow-count"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Memory that can be shared with a smart pointer and then reaquired with a future."
repository = "https://github.com/Vi-Kitten/borrow-count"
readme = "README.md"
keywords = ["async", "signal"]
categories = ["asynchronous"]
rust-version = "1.65.0"

[dependencies]
futures = "0.3.31"

[dev-dependencies]
tokio = { version="1.43.0", features=["full"] }
